spring:
   datasource:
      url: jdbc:h2:file:/tmp/postcode
      driverClassName: org.h2.Driver
      username: sa
      password: password
   jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      hibernate:
         ddl-auto: update

admin:
   username: admin
   password: "{noop}password"